# Generated by Django 4.1 on 2023-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_post',
            name='text',
            field=models.TextField(default='Door Number를 확인해주세요.'),
        ),
    ]
