# Generated by Django 4.1 on 2023-04-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_map_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_post',
            name='floor',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
