# Generated by Django 4.1 on 2023-04-20 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_map_post_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcrions_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=20)),
                ('building_num', models.IntegerField(default='', null=True)),
                ('floor', models.CharField(default='', max_length=20)),
                ('from_place_num', models.IntegerField(default='', null=True)),
                ('to_place_num', models.IntegerField(default='', null=True)),
                ('from_place_name', models.CharField(default='', max_length=20)),
                ('to_place_name', models.CharField(default='', max_length=20)),
                ('img', models.ImageField(upload_to='media/')),
                ('path_name', models.CharField(max_length=20, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
