# Generated by Django 4.1 on 2023-05-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_univ_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ_contacts',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='univ_contacts',
            name='second_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='univ_contacts',
            name='contact',
            field=models.CharField(default='042-280', max_length=20),
        ),
        migrations.AlterField(
            model_name='univ_contacts',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='univ_contacts',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
