# Generated by Django 4.1 on 2023-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_direcrions_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcrions_post',
            name='from_place_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='direcrions_post',
            name='to_place_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
