# Generated by Django 4.1 on 2023-05-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_univ_contacts_position_univ_contacts_second_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ_contacts',
            name='third_contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
