# Generated by Django 4.1 on 2023-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_direcrions_post_from_place_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcrions_post',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
