from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('map/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('directions/<int:pk>/', views.direcions_detail, name='direcions_detail'),
    path('contract/<int:pk>/', views.contracts_detail, name='contract'),
    path('HRC/<int:pk>/', views.HRC, name='HRC'),
    path('MAC_L/<int:pk>/', views.MAC_L, name='MAC_L'),
    path('MAC_M/<int:pk>/', views.MAC_M, name='MAC_M'),
    path('TTD/<int:pk>/', views.TTD, name='TTD'),
    path('EP/<int:pk>/', views.EP, name='EP'),
    path('CH/<int:pk>/', views.CH, name='CH'),
    path('AS/<int:pk>/', views.AS, name='AS'),
    path('SH/<int:pk>/', views.SH, name='SH'),
    path('EN/<int:pk>/', views.EN, name='EN'),
    path('HS/<int:pk>/', views.HS, name='HS'),
    path('BS/<int:pk>/', views.BS, name='BS'),
    path('JL/<int:pk>/', views.JL, name='JL'),
    path('EE/<int:pk>/', views.EE, name='EE'),
    path('OM/<int:pk>/', views.OM, name='OM'),
    path('AD/<int:pk>/', views.AD, name='AD'),
    path('HC/<int:pk>/', views.HC, name='HC'),
    path('TSD/<int:pk>/', views.TSD, name='TSD'),
    path('MM/<int:pk>/', views.MM, name='MM'),
    path('TTA/<int:pk>/', views.TTA, name='TTA'),
    path('TFD/<int:pk>/', views.TFD, name='TFD'),
    path('FS/<int:pk>/', views.FS, name='FS'),
    path('IAC/<int:pk>/', views.IAC, name='IAC'),
]