from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('map/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('directions/<int:pk>/', views.direcions_detail, name='direcions_detail'),
    path('contract/<int:pk>/', views.contracts_detail, name='contract'),
    path('HRC/<int:pk>/', views.HRC, name='HRC_map'),
    path('MAC_L/<int:pk>/', views.MAC_L, name='MAC_L_map'),
    path('MAC_M/<int:pk>/', views.MAC_M, name='MAC_M_map'),
    path('TTD/<int:pk>/', views.TTD, name='TTD_map'),
    path('EP/<int:pk>/', views.EP, name='EP_map'),
    path('CH/<int:pk>/', views.CH, name='CH_map'),
    path('AS/<int:pk>/', views.AS, name='AS_map'),
    path('SH/<int:pk>/', views.SH, name='SH_map'),
    path('EN/<int:pk>/', views.EN, name='EN_map'),
    path('HS/<int:pk>/', views.HS, name='HS_map'),
    path('BS/<int:pk>/', views.BS, name='BS_map'),
    path('JL/<int:pk>/', views.JL, name='JL_map'),
    path('EE/<int:pk>/', views.EE, name='EE_map'),
    path('OM/<int:pk>/', views.OM, name='OM_map'),
    path('AD/<int:pk>/', views.AD, name='AD_map'),
    path('HC/<int:pk>/', views.HC, name='HC_map'),
    path('TSD/<int:pk>/', views.TSD, name='TSD_map'),
    path('MM/<int:pk>/', views.MM, name='MM_map'),
    path('TTA/<int:pk>/', views.TTA, name='TTA_map'),
    path('TFD/<int:pk>/', views.TFD, name='TFD_map'),
    path('FS/<int:pk>/', views.FS, name='FS_map'),
    path('IA/<int:pk>/', views.IA, name='IA_map'),
]