from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('map/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('directions/<int:pk>/', views.direcions_detail, name='direcions_detail'),
    path('contract/<int:pk>/', views.contracts_detail, name='contract'),
    path('HRC/<int:pk>/', views.HRC_map, name='HRC'),
    path('MAC_L/<int:pk>/', views.MAC_L_map, name='MAC_L'),
    path('MAC_M/<int:pk>/', views.MAC_M_map, name='MAC_M'),
    path('TTD/<int:pk>/', views.TTD_map, name='TTD'),
    path('EP/<int:pk>/', views.EP_map, name='EP'),
    path('CH/<int:pk>/', views.CH_map, name='CH'),
    path('AS/<int:pk>/', views.AS_map, name='AS'),
    path('SH/<int:pk>/', views.SH_map, name='SH'),
    path('EN/<int:pk>/', views.EN_map, name='EN'),
    path('HS/<int:pk>/', views.HS_map, name='HS'),
    path('BS/<int:pk>/', views.BS_map, name='BS'),
    path('JL/<int:pk>/', views.JL_map, name='JL'),
    path('EE/<int:pk>/', views.EE_map, name='EE'),
    path('OM/<int:pk>/', views.OM_map, name='OM'),
    path('AD/<int:pk>/', views.AD_map, name='AD'),
    path('HC/<int:pk>/', views.HC_map, name='HC'),
    path('TSD/<int:pk>/', views.TSD_map, name='TSD'),
    path('MM/<int:pk>/', views.MM_map, name='MM'),
    path('TTA/<int:pk>/', views.TTA_map, name='TTA'),
    path('TFD/<int:pk>/', views.TFD_map, name='TFD'),
    path('FS/<int:pk>/', views.FS_map, name='FS'),
    path('IAC/<int:pk>/', views.IAC_map, name='IAC'),
]